// demos/hello-react/src/App.js
const styles = {
  App: {
    textAlign: 'center'
  },
  AppLogo: {
    height: '40vmin',
    pointerEvents: 'none'
  },
  AppHeader: {
    backgroundColor: '#282c34',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    color: 'white'
  },
  AppLink: {
    color: '#61dafb'
  }
};

function App() {
  return (
    <div style={styles.App} className="App">
      <div style={styles.AppHeader} className="App-header">
        <img src="https://img.alicdn.com/imgextra/i4/O1CN01aT5xVM1lbORGlfbfn_!!6000000004837-2-tps-492-437.png" style={styles.AppLogo} className="App-logo" alt="logo" />
        <p>
          Edit <span>src/App.js</span> and save to reload.
        </p>
        <a
          style={styles.AppLink}
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React: https://reactjs.org
        </a>
      </div>
    </div>
  );
}

export default App;

// demos/hello-vue/src/App.vue
<template>
  <div :style="style.home">
    <img alt="Vue logo" src="//img.alicdn.com/imgextra/i3/O1CN01HmN4l21lpai7j2p3H_!!6000000004868-2-tps-200-200.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
    <div :style="style.info">More information about Vue.js</div>
    <div :style="style.info">Visit https://vuejs.org/</div>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

const style = {
  home: {
    display: 'flex',
    position: 'relative',
    flexDirection: 'column',
    margin: '27vw 0vw 0vw',
    padding: '0vw',
    minWidth: '0vw',
    alignItems: 'center',
  },
  info: {
    alignItems: 'center',
    fontSize: '18px',
    margin: '5px 0',
    color: '#555555',
  }
}

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      style,
    }
  },
}
</script>
